### ISSUE TITLE
gonano.dev down

### ISSUE THREAD

**Issue by zQueal** [hectorchu/nano-payment-server#1]
Tried to purchase something from an online retailer today which used NANO, but gonano payments were halted. Looks like they simply used the gonano.dev domain as a payments gateway instead of self-hosting.

After checking, it seems to be down. Server issues, perhaps?

**Comment by hectorchu** [comment]
Yeah I decided that I didn't want the responsibility of funds flowing through my wallet anymore - think it might be breaking money transmitter laws somewhere. The payment server and associated software is all open source on my GitHub so it's possible to run privately.
